Refactor amm methods
galacticcouncil/HydraDX-simulations pull request #150
Opened 2023-08-15 17:11 UTC by jepidoptera

all tests passing

2023-09-04 21:09 UTC, poliwop requested changes
Looks good, very small changes, mostly deleting commented out code and stuff like that.

2023-09-04 21:09 UTC, poliwop commented on hydradx/model/amm/omnipool_amm.py
> -    """Compute new state after LRNA swap"""
This probably should stay "state"?

2023-09-04 21:09 UTC, poliwop commented on hydradx/model/amm/omnipool_amm.py
> +# OmnipoolState.swap = staticmethod(simulate_swap)
Delete these instead of commenting out?

2023-09-04 21:09 UTC, poliwop commented on hydradx/model/amm/stableswap_amm.py
> +    # def execute_remove_liquidity_old(
I think we can delete this

2023-09-04 21:09 UTC, poliwop commented on hydradx/tests/test_omnipool_amm.py
> +    # swap_state, swap_agent = oamm.swap_lrna(initial_state, old_agent, delta_ra, 0, i)
Delete commented out lines?

2023-09-08 20:12 UTC, jepidoptera commented on hydradx/model/run.py
> +        agent_ids = list(new_global_state.agents.keys())
Yes, the list() function itself already creates a new object.

2023-09-08 20:15 UTC, jepidoptera commented on hydradx/model/amm/stableswap_amm.py
> +    # def execute_remove_liquidity_old(
I think so too, we're not going back

2023-09-08 20:42 UTC, jepidoptera commented on hydradx/model/processing.py
> -    if 'deposit_val' in optional_params:
I don't think we use any of this. I've moved into using pu.get_datastream() or just doing this stuff ad-hoc in the notebooks, if it's too case-specific to be standardized in a way that's worth maintaining.

2023-09-08 20:53 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> -    """Compute new state after LRNA swap"""
Yup. Lol

2023-09-11 17:39 UTC, jepidoptera commented on hydradx/model/amm/global_state.py
> +        # this should maybe only work in USD, because we're probably talking about coinbase or something
Not really related to this PR, but that does make sense. I can add it

2023-09-11 20:44 UTC, poliwop approved these changes
Looks good.

2023-09-11 21:20 UTC, merged