Feat liquidations
galacticcouncil/HydraDX-simulations pull request #178
Opened 2024-03-18 19:41 UTC by poliwop

2024-04-11 23:11 UTC, jepidoptera requested changes

2024-04-11 23:11 UTC, jepidoptera commented on hydradx/tests/test_otc.py
> +    if treasury.holdings['DOT'] <= 0:  # treasury should make profit
I think that correct practice is to put this text (treasury should make profit) into an error message, not a comment.

2024-04-11 23:11 UTC, jepidoptera commented on hydradx/tests/test_otc.py
> +    otc.validate()
This doesn't do anything.

2024-04-12 16:17 UTC, poliwop commented on hydradx/model/amm/otc.py
> +        '''sell_amount is the amount of the buy_asset that the agent is selling for the sell_asset.'''
Pycharm is wrong IMO

2024-04-12 16:21 UTC, poliwop commented on hydradx/model/amm/global_state.py
> +def find_partial_liquidation_amount(omnipool: OmnipoolState, cdp: CDP, penalty: float, iters: float = 20, min_amt = 1) -> float:
This is true but I believe the reason for this parameter is rounding error. A parameter for setting minimum value would be implemented differently.
I think I actually implemented this chasing a rounding error bug that turned out to be something else. For now I will try simply setting default value to 0.

2024-04-12 16:29 UTC, poliwop commented on hydradx/model/amm/global_state.py
> +        return
I guess for now an exception is okay if delta_debt > cdp.debt_amt. I think if delta_debt == 0, that is valid and nothing should happen.

2024-04-12 16:48 UTC, poliwop commented on hydradx/model/amm/global_state.py
> +    omnipool_check, agent_check = simulate_swap(
Had to add a case that calculate_sell_from_buy did not handle correctly, but with that change I was also able to make the change you suggest.

2024-04-12 18:07 UTC, jepidoptera approved these changes

2024-04-12 18:11 UTC, merged