Arbitrage with router
galacticcouncil/HydraDX-simulations pull request #182
Opened 2024-04-04 17:11 UTC by jepidoptera

Router doesn't quite implement the whole AMM interface, but it has enough to work for arbitrage.

2024-04-05 21:34 UTC, poliwop requested changes
Mostly looks good, see my comment in test_router.py.. I am not sure we are choosing between withdraw_asset and remove_liquidity correctly.

2024-04-05 22:31 UTC, jepidoptera commented on hydradx/model/amm/omnipool_router.py
> +    def buy_spot(self, tkn_buy: str, tkn_sell: str, fee: float = -1):
You're right, that is a better idea. I'll change it.

2024-04-05 22:32 UTC, jepidoptera commented on hydradx/model/amm/stableswap_amm.py
> +        if type(self.liquidity[tkn_add]) == float or type(self.liquidity[tkn_add]) == int:
That is what it's for, and sure

2024-04-05 22:36 UTC, jepidoptera commented on hydradx/model/amm/arbitrage_agent_general.py
> +    ) if hasattr(buy_ex, 'calculate_buy_from_sell') else float('inf')
No. I added logic at line 272 (buy_ex_sold > buy_ex_max_sell) which addresses this without needing a calculate_buy_from_sell function

2024-04-05 22:39 UTC, jepidoptera commented on hydradx/model/amm/omnipool_router.py
> +        self.omnipool: OmnipoolState = self.exchanges[self.omnipool_id]
Yeah, maybe so. All this does is facilitate intellisense completions and I guess save a few dictionary lookups

2024-04-11 15:11 UTC, poliwop approved these changes
Looks good.

2024-04-11 15:11 UTC, merged