Cdp extend
galacticcouncil/HydraDX-simulations pull request #188
Opened 2024-05-22 15:05 UTC by poliwop

Added money market to model liquidations

2024-06-06 21:43 UTC, jepidoptera requested changes
One general issue I would raise is that using "raise" without indicating a specific exception really isn't best practice, especially when considering future users who may be less familiar with the codebase. I don't think that's a blocking issue but I don't think it's worth considering. Mostly this looks good and pretty thorough, but see the comments.

2024-06-07 15:57 UTC, poliwop commented on hydradx/model/amm/liquidations.py
> +        self.oracles = oracles  # MoneyMarket should never mutate the oracles
That's a good point, I would like to make this change in a future update (I am already making some extensions in a new branch so I will make the change in that branch).

2024-06-07 16:00 UTC, poliwop commented on hydradx/model/amm/global_state.py
> +    cdp = mm.cdps[cdp_i][1]
I am not sure about this, but I agree it's confusing that some use cdp: CDP and some use cdp_i: int.

Some functions make sense outside the context of a money market with an arbitrary CDP, or even applying some parameters of a money market to a CDP that isn't in that money market. For others, you want to enforce that you are the function only applies to CDPs in the money market.

I think however the main use case for having cdp: CDP is to use functions on "fictional" versions of CDPs in the money market, essentially to do "what-if" calculations.

I'll think about if I can do cdp: CDP with everything. Maybe I'll only retain cdp_i: int if it's absolutely necessary that the cdp in question be in the current money market.

2024-06-07 16:04 UTC, poliwop commented on hydradx/model/amm/liquidations.py
> +        assert borrow_amt <= self.liquidity[borrow_asset]
I think you meant it should say
"assert borrow_amt <= self.liquidity[borrow_asset] **-** self.borrowed[borrow_asset]"
right?

2024-06-07 16:05 UTC, poliwop commented on hydradx/model/amm/liquidations.py
> +        if (borrow_asset, collateral_asset) in self.oracles:
Agreed

2024-06-07 16:12 UTC, poliwop commented on hydradx/tests/test_liquidations.py
> +    with pytest.raises(Exception):  # should fail because of missing oracle
Agreed

2024-06-07 16:13 UTC, poliwop commented on hydradx/model/amm/liquidations.py
> +class money_market:
Agreed, I'd like to fix this is the next PR

2024-06-07 16:58 UTC, poliwop commented on hydradx/model/amm/global_state.py
> +    cdp = mm.cdps[cdp_i][1]
Agreed

2024-06-07 19:33 UTC, jepidoptera approved these changes

2024-06-07 20:31 UTC, merged