Lp extension
galacticcouncil/HydraDX-simulations pull request #192
Opened 2024-09-09 15:29 UTC by poliwop

Adds the ability for LPs to have multiple LP positions in Omnipool in the same asset, by making LP positions NFTs. Backward compatible so that LP positions can still be represented by (pool_name, tkn_name) assets in agent holdings.

2024-09-20 21:26 UTC, jepidoptera requested changes
One higher-level critique: I don't know that it makes sense to have these two parallel systems for holding pool shares: nfts and the old system of ('omnipool', tkn). I think the nfts are a better and more flexible solution, and adding all this overhead to maintain backward compatibility seems worse in the long run than just refactoring things to use the new system. This works for now, but I propose simplifying in the next PR.

2024-09-23 17:56 UTC, poliwop commented on hydradx/model/amm/omnipool_amm.py
> +        val = self.calculate_remove_liquidity(agent, quantity, tkn_remove, nft_id)
I agree, this was probably not intentional

2024-09-23 18:07 UTC, poliwop commented on hydradx/tests/test_omnipool_amm.py
> +    single_add_state_2, single_add_agent_2 = oamm.simulate_add_liquidity(initial_state, init_agent, delta_R, tkn,
This is testing adding as an NFT to adding to holdings? I don't think that's redundant?

2024-09-23 18:07 UTC, poliwop commented on hydradx/model/amm/agents.py
>          precision = 10
I'd prefer to address this in a future PR

2024-09-23 18:47 UTC, jepidoptera approved these changes

2024-09-23 18:48 UTC, merged