Dynamic fee tweaks
galacticcouncil/HydraDX-simulations pull request #194
Opened 2024-12-09 18:47 UTC by jepidoptera

implementing changes to the dynamic fee spec

2025-02-03 17:41 UTC, poliwop requested changes
Overall looks good, only minor changes needed. We do need to make sure we are updating dynamic fees on add/remove liquidity. See comments for other change requests.

2025-02-03 17:41 UTC, poliwop commented on hydradx/other tests/test_exploits.py
> +def test_add_liquidity_exploit(lp_multiplier, trade_mult):
remind me why we moved the exploit tests out of integration tests?

2025-02-03 17:41 UTC, poliwop commented on hydradx/notebooks/Omnipool/TestLpFeeDeposit.ipynb
> +{
When I try to run this notebook I get
'TypeError: __init__() got an unexpected keyword argument 'lp_lrna_share''

2025-02-03 17:41 UTC, poliwop commented on hydradx/model/amm/omnipool_amm.py
> +                 lrna_fee_burn: float = 1.0,
Default lrna_fee_burn should be 0.5, since that's what we're doing in PROD. Eventually though we should replace this with parameter sets.

2025-02-03 17:41 UTC, poliwop commented on hydradx/tests/test_omnipool_amm.py
> +    assert fee == pytest.approx(fee2, rel=1e-20)
Is this first test just the code of my original test? I don't think we need it anymore, at least not in integration tests.

2025-02-03 17:41 UTC, poliwop commented on hydradx/tests/test_omnipool_amm.py
> +    assert fee4 == pytest.approx(fee3, rel=1e-08)
Can we at least fuzz num_blocks? I want to know that this works for num_blocks = 0, 1, and 2 especially (to check for off-by-1 errors). According to my testing, this works, let's just fuzz num_blocks so that we check it?

2025-02-03 17:41 UTC, poliwop commented on hydradx/other tests/test_exploits.py
> +        lrna_fee_burn=1.0,
We need to test with lrna_fee_burn = 0.5 since that's what will be happening in PROD

2025-02-03 23:18 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +    _lrna_fee: DynamicFee
It will still work, because the class level declarations are just default values. If you give specific values for an instance, it will override those (without affecting any other instance). That said, there's actually no reason these lines need to be there.

The potential problem I do see is that there's no mechanism to prevent two OmnipoolState objects from sharing the same "unique" ID. There could be a class variable to track which ones have been used, object if one is re-used, and auto-generate a unique one if none is provided.

2025-02-03 23:22 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +        self.last_liquidity = liquidity if liquidity is not None else {}
I think that's a good way to make it clearer

2025-02-03 23:25 UTC, jepidoptera commented on hydradx/notebooks/Omnipool/TestLpFeeDeposit.ipynb
> +{
I should probably just delete the notebook, since we decided against using that mechanism

2025-02-03 23:25 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +        # knowing there have been no trades until now
Added fee update to add/remove liquidity.

2025-02-04 19:13 UTC, jepidoptera commented on requirements.txt
> +requests~=2.32.0
I think it's not necessary. I'll roll back

2025-02-04 19:15 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +                 lrna_fee_burn: float = 1.0,
done

2025-02-04 19:49 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +        w_term = (w * (math.pow(w, m) - math.pow(w, num_blocks))) / self.oracles['price'].decay_factor
You're right, that's a little simpler

2025-02-04 20:10 UTC, jepidoptera commented on hydradx/other tests/test_exploits.py
> +def test_add_liquidity_exploit(lp_multiplier, trade_mult):
I put them back

2025-02-04 20:11 UTC, jepidoptera commented on hydradx/tests/test_omnipool_amm.py
> +    assert fee4 == pytest.approx(fee3, rel=1e-08)
done

2025-02-04 20:12 UTC, jepidoptera commented on hydradx/other tests/test_exploits.py
> +        lrna_fee_burn=1.0,
done

2025-02-04 20:15 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
>          else:
I added a comment to clarify that it should be a number. I didn't specifically enforce this because it could plausibly be a float, an int (0) an mpf, or some other kind of number

2025-02-04 20:16 UTC, jepidoptera commented on hydradx/model/amm/omnipool_amm.py
> +    _lrna_fee: DynamicFee
I deleted these lines because they don't do anything and might be confusing

2025-02-07 16:38 UTC, poliwop requested changes
Mostly fine, I think the default parameter fix for Omnipool was not quite correct. I would also extend the multi-block test to include num_blocks=0 if possible? I think that should work?

2025-02-07 21:00 UTC, poliwop approved these changes
Looks good.

2025-02-07 21:10 UTC, merged